import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import sqlite3
from pathlib import Path

# Path to the database
db_path = Path("data/tiger_research.db")

def migrate_db():
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Check if log_id exists in logs
    try:
        cursor.execute("SELECT log_id FROM logs LIMIT 1")
    except sqlite3.OperationalError:
        print("Migrating logs table...")
        cursor.execute("ALTER TABLE logs RENAME TO logs_old;")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                log_id TEXT UNIQUE,
                level TEXT NOT NULL,
                module TEXT,
                message TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                meta_json TEXT
            )
        """)
        # Insert old data with autogenerated dummy log_ids
        cursor.execute("""
            INSERT INTO logs (id, log_id, level, module, message, created_at, meta_json)
            SELECT id, 'legacy_' || id, level, module, message, created_at, meta_json FROM logs_old;
        """)
        cursor.execute("DROP TABLE logs_old;")
        conn.commit()
    
    # Check if log_id exists in process_timings
    try:
        cursor.execute("SELECT log_id FROM process_timings LIMIT 1")
    except sqlite3.OperationalError:
        print("Migrating process_timings table...")
        cursor.execute("ALTER TABLE process_timings RENAME TO process_timings_old;")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS process_timings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                log_id TEXT UNIQUE,
                operation TEXT NOT NULL,
                duration_seconds REAL,
                start_time TIMESTAMP,
                end_time TIMESTAMP,
                meta_json TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute("""
            INSERT INTO process_timings (id, log_id, operation, duration_seconds, start_time, end_time, meta_json, created_at)
            SELECT id, 'legacy_' || id, operation, duration_seconds, start_time, end_time, meta_json, created_at FROM process_timings_old;
        """)
        cursor.execute("DROP TABLE process_timings_old;")
        conn.commit()

    conn.close()
    print("Migration complete!")

if __name__ == "__main__":
    if db_path.exists():
        migrate_db()
    else:
        print("DB does not exist. No migration needed.")
